### ISSUE TITLE
Pyodide Load Timeout

### ISSUE THREAD

**Issue by ElliotRoe** [BX-Coding/patch-vm#78]
***Summary***
Pyodide load times out on fresh load with no caches resulting in infinite loading screen
***Steps to reproduce***
1. Clear cookies
2. Refresh
3. Default project does not load
4. Open console

***Current Behavior***
Pyodide is timing out

***Expected behavior***
Pyodide should load normally

**Comment by ElliotRoe** [comment]
https://github.com/BX-Coding/patch-vm/blob/c899362e3b39bd2baf7215587838db0d6c30328b/src/worker/pyatch-worker.mjs#L55

**Comment by azure-kyuri** [comment]
adding a loading bar may be helpful when Pyodide is loading

**Comment by azure-kyuri** [comment]
- happens on first load
- (may only be live production?) Double check this

**Comment by azure-kyuri** [comment]
sometimes it loads with throttling, and with clearing cache it may or may not load. (It loaded on Elliot's end but still not sure)
